### ISSUE TITLE
Not Working in Windows

### ISSUE THREAD

**Issue by kashyapndps00** [cracker911181/Cracker-Tool#23]
**Environment**
- Windows 10
- Python Installed

**Expected Behavior:**
The Script should Work

**Current Behavior:**
_Error:_
```
C:\Users\Acer\hacker\Cracker-Tool>python cracker-main.py
python: can't open file 'C:\\Users\\Acer\\hacker\\Cracker-Tool\\cracker-main.py': [Errno 22] Invalid argument
```

Please Fix or Tell Me How To Use in Windows

**Comment by cracker911181** [comment]
It's not for windows. It's only for termux.
